version: "2"
networks:
  znsxnet:
services:
  #influx
  znsx-influx:
    image: influxdb:1.8.10
    restart: always
    container_name: znsx-influx
    logging:
      driver: json-file
      options:
        max-size: "20M" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    ports:
      - 58086:8086
    environment:
      TZ: Asia/Shanghai
    networks:
      znsxnet:
        aliases:
          - hsrg-influx
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/znsx/data/influx:/var/lib/influxdb

  #mongo
  znsx-mongo:
    image: mongo:latest
    restart: always
    container_name: znsx-mongo
    logging:
      driver: json-file
      options:
        max-size: "20M" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    ports:
      - 57017:27017
    environment:
      TZ: Asia/Shanghai
    #      MONGO_INITDB_ROOT_USERNAME: root
    #      MONGO_INITDB_ROOT_PASSWORD: hsrg8888
    networks:
      znsxnet:
        aliases:
          - hsrg-mongo
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/znsx/data/mongodb:/data/db

  #redis
  znsx-redis:
    image: redis:7
    restart: always
    container_name: znsx-redis
    logging:
      driver: json-file
      options:
        max-size: "20M" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    ports:
      - 56379:6379
    environment:
      TZ: Asia/Shanghai
    networks:
      znsxnet:
        aliases:
          - hsrg-redis
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/znsx/data/redis:/data

  #mariadb
  znsx-mariadb:
    image: mariadb:latest
    restart: always
    container_name: znsx-mariadb
    logging:
      driver: json-file
      options:
        max-size: "20M" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    ports:
      - 53306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: hsrg8888
      character-set-server: utf8
    privileged: true
    networks:
      znsxnet:
        aliases:
          - hsrg-mysql
    volumes:
      - /home/znsx/data/mariadb/:/var/lib/mysql
      - /etc/localtime:/etc/localtime

  #emqx
  znsx-emqx:
    image: emqx:5.0.17
    restart: always
    container_name: znsx-emqx
    logging:
      driver: json-file
      options:
        max-size: "20M" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    ports:
      - 1883:1883
      - 8083:8083
      # - 8883:8883
      - 18083:18083
    environment:
      TZ: Asia/Shanghai
    networks:
      znsxnet:
        aliases:
          - hsrg-emqx
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/znsx/data/emqx/etc:/opt/emqx/etc
      - /home/znsx/data/emqx/log:/opt/emqx/log

  # #mysqladmin服务
  # mysqladmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: "20M" # 单个文件大小为200k
  #       max-file: "10" # 最多10个文件
  #   ports:
  #     - 8080:80
  #   environment:
  #     TZ: Asia/Shanghai
  #     PMA_HOST: hsrg-mysql
  #   privileged: true
  #   networks:
  #     znsxnet:
  #       aliases:
  #         - phpmyadmin

  #mmhg服务
  znsx-mmhg:
    image: mono-jdk:v1
    restart: always
    container_name: znsx-mmhg
    logging:
      driver: json-file
      options:
        max-size: "20M" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    ports:
      - 58006:5005/tcp
      - 10023:10023/tcp
    environment:
      TZ: Asia/Shanghai
    privileged: true
    networks:
      znsxnet:
        aliases:
          - hsrg-mmhg
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/znsx/program/mmhg/start.sh:/docker-entrypoint.sh
      - /home/znsx/program/mmhg:/opt/app
      - /home/:/home/
    depends_on:
      - znsx-web

  #bt-gateway服务
  znsx-bt-gateway:
    image: hsrg-jdk:11
    restart: always
    container_name: znsx-bt-gateway
    logging:
      driver: json-file
      options:
        max-size: "20M" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    ports:
      - 28009:5005/tcp
      - 62080:80/tcp
      - 62020:62020/udp
      - 62021:62021/tcp
    environment:
      TZ: Asia/Shanghai
    privileged: true
    networks:
      znsxnet:
        aliases:
          - hsrg-bt-gateway
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
      - /home/znsx/program/bt-gateway/start.sh:/docker-entrypoint.sh
      - /home/znsx/program/bt-gateway:/opt/app
    depends_on:
      - znsx-redis
      - znsx-emqx

  # #acserver服务
  # znsx-acserver:
  #   image: hsrg-jdk:11
  #   restart: always
  #   container_name: znsx-acserver
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: "20M" # 单个文件大小为200k
  #       max-file: "10" # 最多10个文件
  #   ports:
  #     - 8888:8888
  #     - 10604:10604/udp
  #     - 10352:10352/udp
  #   environment:
  #     TZ: Asia/Shanghai
  #   privileged: true
  #   networks:
  #     znsxnet:
  #       aliases:
  #         - hsrg-acserver
  #   volumes:
  #     - /etc/localtime:/etc/localtime
  #     - /home/znsx/program/acserver/docker-entrypoint.sh:/docker-entrypoint.sh
  #     - /home/znsx/program/acserver:/opt/app
  #   depends_on:
  #     - znsx-emqx

  #----------------------------------------------znsx app 1 --------------------------------

  #nginx服务
  znsx-nginx:
    image: nginx:1.23
    restart: always
    container_name: znsx-nginx
    logging:
      driver: json-file
      options:
        max-size: "20M" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      TZ: Asia/Shanghai
    privileged: true
    networks:
      znsxnet:
        aliases:
          - hsrg-nginx
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/znsx/program/web-front/:/usr/share/nginx/
      - /home/fileData/report/img/:/usr/share/nginx/www/image/
      - /home/fileData/autograph/:/usr/share/nginx/www/autograph/
      - /home/fileData/headerImage/:/usr/share/nginx/www/headerImage/
      - /home/fileData/report/img/:/usr/share/nginx/admin/image/
      - /home/fileData/autograph/:/usr/share/nginx/admin/autograph/
      - /home/fileData/headerImage/:/usr/share/nginx/admin/headerImage/
      - /home/znsx/program/web-front/conf/:/etc/nginx/conf.d/
      - /home/znsx/log/:/var/log/nginx

  #算法服务
  znsx-midas:
    image: python3.6:v2
    restart: always
    container_name: python3.6
    logging:
      driver: json-file
      options:
        max-size: "20M" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    ports:
      - 5000:5000/tcp
    environment:
      TZ: Asia/Shanghai
    privileged: true
    networks:
      znsxnet:
        aliases:
          - hsrg-midas
    volumes:
      - /etc/localtime:/etc/localtime
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/env/:/opt/env/
      - /home/znsx/program/algorithm/midas/:/usr/local/lib/python3.6/site-packages/midas/
      - /home/znsx/data/reportPath/:/home/znsx/data/reportPath/
      - /home/fileData/report/:/home/fileData/report/
      - /home/znsx/log:/home/znsx/log
    command: [ "pyc.sh" ]
    depends_on:
      - znsx-influx


  #----------------------------------------------znsx app 2 --------------------------------
  # biz服务
  znsx-biz:
    image: hsrg-jdk:11
    restart: always
    container_name: znsx-biz
    logging:
      driver: json-file
      options:
        max-size: "20M" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    ports:
      - 58000:5005/tcp
      - 52014:52014/udp
      - 62014:62014/udp
      - 62024:62024/tcp
      - 62025:62025/tcp
      - 15035:15035/udp
      - 63014:63014/tcp
    environment:
      TZ: Asia/Shanghai
    privileged: true
    networks:
      znsxnet:
        aliases:
          - hsrg-biz
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/env/:/opt/env/
      - /home/znsx/program/biz/start.sh:/docker-entrypoint.sh
      - /home/znsx/program/biz/:/opt/app/
      - /home/znsx/:/home/znsx/
    depends_on:
      - znsx-redis
      - znsx-emqx

  #db服务
  znsx-db:
    image: hsrg-jdk:11
    restart: always
    container_name: znsx-db
    logging:
      driver: json-file
      options:
        max-size: "20M" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    ports:
      - 58001:5005/tcp
    environment:
      TZ: Asia/Shanghai
    privileged: true
    networks:
      znsxnet:
        aliases:
          - hsrg-db
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/znsx/program/db/start.sh:/docker-entrypoint.sh
      - /home/znsx/program/db/:/opt/app/
      - /home/znsx/:/home/znsx/
    depends_on:
      - znsx-redis
      - znsx-emqx
      - znsx-influx

  #task服务
  znsx-task:
    image: hsrg-jdk:11
    restart: always
    container_name: znsx-task
    logging:
      driver: json-file
      options:
        max-size: "20M" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    ports:
      - 58005:5005/tcp
    environment:
      TZ: Asia/Shanghai
    privileged: true
    networks:
      znsxnet:
        aliases:
          - hsrg-db
    volumes:
      - /etc/localtime:/etc/localtime
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/znsx/program/task/start.sh:/docker-entrypoint.sh
      - /home/znsx/program/task/:/opt/app/
      - /home/:/home/
    depends_on:
      - znsx-influx
      - znsx-mariadb
  znsx-web:
    image: hsrg-jdk:11
    restart: always
    container_name: znsx-web
    logging:
      driver: json-file
      options:
        max-size: "20M" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    ports:
      - 58003:5005/tcp
      - 8081:8081/tcp
      - 62015:62015/tcp
    environment:
      TZ: Asia/Shanghai
    privileged: true
    networks:
      znsxnet:
        aliases:
          - hsrg-web
    volumes:
      - /etc/localtime:/etc/localtime
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/znsx/program/web/start.sh:/docker-entrypoint.sh
      - /home/znsx/program/web/:/opt/app/
      - /home/:/home/
    depends_on:
      - znsx-mariadb
      - znsx-redis
      - znsx-influx
      - znsx-mongo

  #----------------------------------------------support app--------------------------------
  support-emqx:
    image: emqx:5.0.17
    restart: always
    container_name: support-emqx
    logging:
      driver: json-file
      options:
        max-size: "20M" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    ports:
      - 2883:1883/tcp
      - 2083:8083/tcp
      - 28083:18083/tcp
      # - 28883:8883/udp
    environment:
      TZ: Asia/Shanghai
    networks:
      znsxnet:
        aliases:
          - support-emqx
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/znsx/data/support_emqx/etc:/opt/emqx/etc
      - /home/znsx/data/support_emqx/log:/opt/emqx/log

  #db服务
  support-db:
    image: hsrg-jdk:11
    restart: always
    container_name: support-db
    logging:
      driver: json-file
      options:
        max-size: "20M" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    ports:
      - 28001:5005/tcp
    environment:
      TZ: Asia/Shanghai
    privileged: true
    networks:
      znsxnet:
        aliases:
          - support-db
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
      - /home/znsx/program/supportDb/start.sh:/docker-entrypoint.sh
      - /home/znsx/program/supportDb/:/opt/app/
      - /home/znsx/:/home/znsx/
    depends_on:
      - znsx-redis
      - znsx-influx
      - support-emqx

  support-biz:
    image: hsrg-jdk:11
    restart: always
    container_name: support-biz
    logging:
      driver: json-file
      options:
        max-size: "20M" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    ports:
      - 28000:5005/tcp
      - 7012:52014/udp
      - 7014:62014/udp
    environment:
      TZ: Asia/Shanghai
    privileged: true
    networks:
      znsxnet:
        aliases:
          - support-biz
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
      - /home/znsx/program/supportBiz/start.sh:/docker-entrypoint.sh
      - /home/znsx/program/supportBiz:/home/znsx/program/supportBiz
      - /home/znsx/:/home/znsx/
    depends_on:
      - znsx-redis
      - support-emqx

  support-web:
    image: hsrg-jdk:11
    restart: always
    container_name: support-web
    logging:
      driver: json-file
      options:
        max-size: "20M" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    ports:
      - 28003:5005/tcp
      - 7777:7777/tcp
      - 7015:7015/tcp
    environment:
      TZ: Asia/Shanghai
    privileged: true
    networks:
      znsxnet:
        aliases:
          - support-web
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
      - /home/znsx/program/supportWeb/start.sh:/docker-entrypoint.sh
      - /home/znsx/program/supportWeb/:/opt/app/
      - /home/:/home/
    depends_on:
      - support-emqx
      - znsx-mariadb
      - znsx-redis
      - znsx-influx
      - znsx-mongo
